// Copyright 2021 The excelize-rs Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.

//! excelize-rs is a library written in pure Rust providing a set of functions
//! that allow you to write to and read from XLSX / XLSM / XLTM files. Supports
//! reading and writing spreadsheet documents generated by Microsoft Excel&trade;
//! 2007 and later.
//!
//! # Reading spreadsheet
//!
//! The following constitutes the bare to read a spreadsheet document.
//!
//! ```rust
//! extern crate excelize_rs;
//!
//! use excelize_rs::*;
//!
//! fn main() {
//!     let path = String::from("Book1.xlsx");
//!     let wb = Spreadsheet::open_file(path);
//!     match wb {
//!         Ok(ws) => match ws.get_cell_value("Sheet1", 1, 1) {
//!             Ok(c) => {
//!                 let cell = String::from(c);
//!                 println!("the value of cell A1 is: {}", cell)
//!             }
//!             Err(e) => println!("{:?}", e),
//!         },
//!         Err(e) => print!("{:?}", e),
//!     }
//! }
//! ```
pub mod cell;
pub mod errors;
pub mod excelize;
pub mod rels;
pub mod sst;
pub mod utils;
pub mod workbook;
pub mod worksheet;
pub mod xml_content_types;
pub mod xml_rels;
pub mod xml_sst;
pub mod xml_workbook;
pub mod xml_worksheet;

pub use cell::*;
pub use errors::*;
pub use excelize::*;
pub use rels::*;
pub use sst::*;
pub use utils::*;
pub use workbook::*;
pub use worksheet::*;
pub use xml_content_types::*;
pub use xml_rels::*;
pub use xml_sst::*;
pub use xml_workbook::*;
pub use xml_worksheet::*;
